### ISSUE TITLE
Sermon Series Creation & Editing

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialAPI#10]
## US
As a developer, I want to be able to easily add documents to Mongo by just simply making a REST call.

## AC
- [x] A new sermon series should appear in mongo when a new sermon series is starting
- [x] An existing sermon series should be updated when a user requests an update -> simply changing the name for example or ending the series -> defining an End Date. This route should NOT be used to add new messages
- [x] Another route should exist solely to Add / edit messages within a sermon series

### Tasks
- [x] Do the thing
