### ISSUE TITLE
Recently Played

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialAPI#16]
## US
As a user I want to be able to know what videos I had been playing recently, and have those display themselves first so that I can see if I want to keep watching from where I left off.

### AC
- [x] Users can watch their videos from where they left off.
- [x] User data is stored anonymously in the DB, and new users are assigned GUIDs based on their device ID.

### Tasks
- [x] Create recently watched collection in Mongo
- [x] Create a reference to the Sermon `MessageId` that the user was watching.

**Comment by ksigWyatt** [comment]
User Ids will be the Device Id of the requesting device; in swift the syntax is 
`UIDevice.currentDevice().identifierForVendor!.UUIDString`

**Comment by ksigWyatt** [comment]
Considerations; What if a user buys a new device, or what happens when we have a large collection of users because everyone has bought a new device and we just have a huge list of everyone's UIDs in a mongo collection. It should be cleared out every 60 days or so.

However, I still don't think that this will constitute the need for a Microservice. We can do something similar to what we do when we are looking for the expire timer for the livestream. ALSO however, if the API ever goes down - this thread will be lost if it is only initialized from an API request when we create a new log for some user. 

As a result, we should include a method that gets called on startup to look in mongo for the device UIDs and sees when the `RecentlyPlayedLogging` Document was last modified in the new `RecentlyPlayedLogging` collection.

**Comment by ksigWyatt** [comment]
Will need to flesh out some AC from these new observations

**Comment by ksigWyatt** [comment]
With the new addition of these AC items, the Scope has increased drastically. Might think at making this 2 stories. One with the main thought of recently watched and another for cleanup / threading.

**Comment by ksigWyatt** [comment]
Removing these stories as this will be done and managed on the client side.

**Comment by ksigWyatt** [comment]
Will need to remove this infrastructure and rollback these changes
