### ISSUE TITLE
Recently Played Logging

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialAPI#17]
## AC
- [ ] Recently played collection will be cleared every 60 days, meaning that we will drop all documents from the collection every 60 days. (unless it was recently added - We will need a timestamp to determine when it was last updated. If it was last updated within 60 days) we will not delete it.
- [ ] Async thread that will run on startup to determine what day it is, and when it has been 60 days, we should find the documents to delete (see above) and then delete those.
- [ ] Cache the create date for the first item, since visiting mongo is not needed unless a doc is inserted. At which point we should just update the cache again in addition to the Mongo logging collection.

### Tasks
- [ ] Create a recently watched logging collection, to contain the last time that the collection was updated as well as when it was created / first document inserted.
- [ ] Create a async startup thread that will check only ONCE a day to determine if the collection above should be purged of old data. 
- [ ] We need to verify that this async thread will not inhibit the performance of the API and that we only instantiate it ONE TIME on startup. Meaning that if the service fails, when it restarts - the service will automatically have this worker thread running. [NO MEM LEAKS!!!!]
- [ ] In order to avoid memory leaks through this, we "could" create a cache for this information in memory, that way if we see another thread that is not the worker thread we want to have access to this, we can return and / or kill that thread.

**Comment by ksigWyatt** [comment]
We might be able to extract a lot of this logic to the client and could cause this story to be closed. Because this is a story that is already very large in scope and could become bigger.

**Comment by ksigWyatt** [comment]
Removing these stories as this will be done and managed on the client side.
