### ISSUE TITLE
Paging on Sermon Series Summaries - GET /sermons

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialAPI#20]
## US
As a developer I want to be able to get paged results for my sermons, so that performance is not affected when the data set is large.

### AC
- [x] Request contract should not change
- [x] response should contain 5 on the first page and 10 on every page after that, including the number of pages
- [x] Response should contain page info

### Tasks
- [x] :justdoit:
