### ISSUE TITLE
Determine deployment strategy

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialAPI#22]
## Task
- [x] Determine easy deployment strategy to our Azure server
- [x] Deployments can easily override each other in PROD, so that there's no real downtime
- [x] Test Azure deployments

**Comment by ksigWyatt** [comment]
Process is repeatable
