### ISSUE TITLE
Base Class Changes and Generically Typed response Messages

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialAPI#23]
### Task
- [x] Change the `GenericMongoRepo` to include the logic for the connection string and init our `MongoConnection`
- [ ] ~~Change the `BaseRepo` to include all the `REST` methods that can handle generic objects and messages being sent through them~~
_Stretch Goal_
- [x] Create a generic typed response message for services, methods, repos so we can check for errors and what not as the application is executing
- [x] Return correct HTTP responses, `OK`, `BadRequest`, `Unauthorized` etc where it makes sense
- [x] Clean things up

**Comment by ksigWyatt** [comment]
As part of this effort we also need to change the LiveStream object to not include the slug and title since we can't go directly to the video on Facebook anyways, and we don't use the title that makes this a lot more difficult to POST a new object on Sunday Morning
