### ISSUE TITLE
Security & Rate Limiting

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialAPI#32]
## Task
- [x] Enable Rate Limiting
- [ ] Enforce Authentication on Mongo Instances
- [x] Stretch Goal: Enforce Auth Headers on API calls; whitelist only

**Comment by ksigWyatt** [comment]
Rate limiting can be defined in your appSettings.json
