### ISSUE TITLE
Enable live-stream to be reset after the stream has stopped

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialAPI#6]
## US
As a developer I don't want to have to make another PUT request for the live-stream to update that the system is no longer live-streaming.

## AC
- [x] The live-stream notification will disappear when the live-stream is over (Polling the Timestamp).
- [x] Any attempts to connect to the live-stream after the stream is over will return a LiveStream object indicating that the stream is not active.
- [x] Make a polling route for the Client to call at the same time, so others can easily see if the stream is active.
- [x] Create an expiring Cache for this isLive setting and we can poll IsLive that in memory, if the cache has been disposed after the expiration time, go to mongo one time and grab the info and store it in the cache again.
- [x] Calculate for the Client how long they can safely wait until they can request again / time until the value will change -> this might help us with many requests at random times and help a UI developer to know how long they should wait to request again or for them to know "I have 20 minutes left until this is over"

### Tasks
- [x] Using a Timestamp for a global timeout?
- [x] Facebook API for live-streaming to see if a stream is active?
- [x] Return a more consumable response from LiveSermons to something like LiveSermonsResponse that contains something similar to the LiveSermons object but an outer IsLive that can be easily read.
- [x] Enable an expiry cache, using `HttpRuntime.Cache()` -> great for constant time lookups

## UI related stories for TCOA (Swift)
- [ ] ~~When someone is viewing the stream, we should poll the API every few seconds and see if there is still a stream, if `IsLive` is still `true` then keep playing, otherwise close the player and reload the screen to remove the live notification.~~
_This is being worked as part of this story for AC 1/3_

**Comment by ksigWyatt** [comment]
So integrating with the Facebook API will not work https://developers.facebook.com/docs/apps/review/feature/

**Comment by ksigWyatt** [comment]
I will be forced to enable a quick deployment of a slug given to us from facebook once a week. This seems really annoying.

**Comment by ksigWyatt** [comment]
I might want to look at what the best way for some kind of async job that runs once the LiveSermon object has been updated to then go back and change the values for isLive once the expiration timer is up. A MS seems like it might be overkill here, I wonder if we could have a long running thread that checks every so often, the ExpirationTime in mongo to see if the value is later than now.

**Comment by ksigWyatt** [comment]
Look at this for the interval timing of seeing when a stream's timer has expired https://stackoverflow.com/questions/30462079/run-async-method-regularly-with-specified-interval

**Comment by ksigWyatt** [comment]
Updated AC:
- When a user is viewing the stream, and the timer expires -> we will need to update the flag in the database. But the client won't know that the stream is no longer active. The LOE on the Client is slightly low, but hitting mongo a bunch of times is going to get harsh.
- Much less expensive than going to mongo for every Client, every 10ms for over an hour. That might cause issues.

**Comment by ksigWyatt** [comment]
This is going to require some thorough testing since this is largely an async method.

**Comment by ksigWyatt** [comment]
Testing this
